export const SUPERADMIN_DASHBOARD_REQUEST = "SUPERADMIN_DASHBOARD_REQUEST";
export const SUPERADMIN_DASHBOARD_SUCCESS = "SUPERADMIN_DASHBOARD_SUCCESS";
export const SUPERADMIN_DASHBOARD_FAIL    = "SUPERADMIN_DASHBOARD_FAIL";

export const SUPERADMIN_COMMISSIONS_REQUEST = "SUPERADMIN_COMMISSIONS_REQUEST";
export const SUPERADMIN_COMMISSIONS_SUCCESS = "SUPERADMIN_COMMISSIONS_SUCCESS";
export const SUPERADMIN_COMMISSIONS_FAIL    = "SUPERADMIN_COMMISSIONS_FAIL";

export const SUPERADMIN_SELLER_COMMISSIONS_REQUEST = "SUPERADMIN_SELLER_COMMISSIONS_REQUEST";
export const SUPERADMIN_SELLER_COMMISSIONS_SUCCESS = "SUPERADMIN_SELLER_COMMISSIONS_SUCCESS";
export const SUPERADMIN_SELLER_COMMISSIONS_FAIL    = "SUPERADMIN_SELLER_COMMISSIONS_FAIL";

export const SUPERADMIN_USERS_REQUEST = "SUPERADMIN_USERS_REQUEST";
export const SUPERADMIN_USERS_SUCCESS = "SUPERADMIN_USERS_SUCCESS";
export const SUPERADMIN_USERS_FAIL    = "SUPERADMIN_USERS_FAIL";

export const SUPERADMIN_UPDATE_USER_REQUEST = "SUPERADMIN_UPDATE_USER_REQUEST";
export const SUPERADMIN_UPDATE_USER_SUCCESS = "SUPERADMIN_UPDATE_USER_SUCCESS";
export const SUPERADMIN_UPDATE_USER_FAIL    = "SUPERADMIN_UPDATE_USER_FAIL";
export const SUPERADMIN_UPDATE_USER_RESET   = "SUPERADMIN_UPDATE_USER_RESET";

export const SUPERADMIN_DELETE_USER_REQUEST = "SUPERADMIN_DELETE_USER_REQUEST";
export const SUPERADMIN_DELETE_USER_SUCCESS = "SUPERADMIN_DELETE_USER_SUCCESS";
export const SUPERADMIN_DELETE_USER_FAIL    = "SUPERADMIN_DELETE_USER_FAIL";
export const SUPERADMIN_DELETE_USER_RESET   = "SUPERADMIN_DELETE_USER_RESET";

export const SUPERADMIN_SELLERS_REQUEST = "SUPERADMIN_SELLERS_REQUEST";
export const SUPERADMIN_SELLERS_SUCCESS = "SUPERADMIN_SELLERS_SUCCESS";
export const SUPERADMIN_SELLERS_FAIL    = "SUPERADMIN_SELLERS_FAIL";

export const SUPERADMIN_PRODUCTS_REQUEST = "SUPERADMIN_PRODUCTS_REQUEST";
export const SUPERADMIN_PRODUCTS_SUCCESS = "SUPERADMIN_PRODUCTS_SUCCESS";
export const SUPERADMIN_PRODUCTS_FAIL    = "SUPERADMIN_PRODUCTS_FAIL";

export const SUPERADMIN_DELETE_PRODUCT_REQUEST = "SUPERADMIN_DELETE_PRODUCT_REQUEST";
export const SUPERADMIN_DELETE_PRODUCT_SUCCESS = "SUPERADMIN_DELETE_PRODUCT_SUCCESS";
export const SUPERADMIN_DELETE_PRODUCT_FAIL    = "SUPERADMIN_DELETE_PRODUCT_FAIL";
export const SUPERADMIN_DELETE_PRODUCT_RESET   = "SUPERADMIN_DELETE_PRODUCT_RESET";

export const SUPERADMIN_ORDERS_REQUEST = "SUPERADMIN_ORDERS_REQUEST";
export const SUPERADMIN_ORDERS_SUCCESS = "SUPERADMIN_ORDERS_SUCCESS";
export const SUPERADMIN_ORDERS_FAIL    = "SUPERADMIN_ORDERS_FAIL";

export const SUPERADMIN_DELETE_ORDER_REQUEST = "SUPERADMIN_DELETE_ORDER_REQUEST";
export const SUPERADMIN_DELETE_ORDER_SUCCESS = "SUPERADMIN_DELETE_ORDER_SUCCESS";
export const SUPERADMIN_DELETE_ORDER_FAIL    = "SUPERADMIN_DELETE_ORDER_FAIL";
export const SUPERADMIN_DELETE_ORDER_RESET   = "SUPERADMIN_DELETE_ORDER_RESET";

export const SUPERADMIN_MARK_PAID_REQUEST = "SUPERADMIN_MARK_PAID_REQUEST";
export const SUPERADMIN_MARK_PAID_SUCCESS = "SUPERADMIN_MARK_PAID_SUCCESS";
export const SUPERADMIN_MARK_PAID_FAIL    = "SUPERADMIN_MARK_PAID_FAIL";
export const SUPERADMIN_MARK_PAID_RESET   = "SUPERADMIN_MARK_PAID_RESET";

export const SUPERADMIN_UPDATE_COMMISSION_REQUEST = "SUPERADMIN_UPDATE_COMMISSION_REQUEST";
export const SUPERADMIN_UPDATE_COMMISSION_SUCCESS = "SUPERADMIN_UPDATE_COMMISSION_SUCCESS";
export const SUPERADMIN_UPDATE_COMMISSION_FAIL    = "SUPERADMIN_UPDATE_COMMISSION_FAIL";
export const SUPERADMIN_UPDATE_COMMISSION_RESET   = "SUPERADMIN_UPDATE_COMMISSION_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
